### ISSUE TITLE
Option to select backend

### ISSUE THREAD

**Issue by robinvanemden** [wasmerio/wasmer-go#104]
### Motivation

See also [Wasmer issue 605](https://github.com/wasmerio/wasmer/issues/605) : It would be great if it would be possible to dynamically choose different back-ends, instead of defaulting to Cranelift. For instance, the LLVM back-end might be preferred for the speed of execution of the output, and also features like SIMD that are currently exclusive to LLVM (though for the latter, SIMD would first need to be exposed through the C API, see [here](https://github.com/wasmerio/wasmer/issues/1108)).

### Proposed solution

Expose compile_with - first in C API, then in go-ext-wasm.

**Comment by Hywan** [comment]
Thanks for opening the issue!
