### ISSUE TITLE
data structure passed through InstanceContext isn't preserved 

### ISSUE THREAD

**Issue by noot** [wasmerio/wasmer-go#135]
### Describe the bug

Hey, I'm currently using wasmer in [gossamer](https://github.com/ChainSafe/gossamer). In our usage of wasmer, we pass in a `Ctx` struct as the `InstanceContext` [here](https://github.com/ChainSafe/gossamer/blob/noot/execute-block/lib/runtime/runtime.go#L32). We instantiate the module [here](https://github.com/ChainSafe/gossamer/blob/noot/execute-block/lib/runtime/runtime.go#L59). The `Storage` field in the struct has an underlying trie data structure. (relevant code is [here](https://github.com/ChainSafe/gossamer/blob/noot/execute-block/dot/state/storage.go) and [here](https://github.com/ChainSafe/gossamer/blob/noot/execute-block/lib/trie/trie.go)) The instance imports various go functions [here](https://github.com/ChainSafe/gossamer/blob/noot/execute-block/lib/runtime/imports_old.go) that use `Storage` to manipulate the trie key-values. 

I've noticed that between calls to the imported functions, the trie values become incorrect (I've verified this isn't an issue with the actual trie structure by replicating the key-values that are being inserted)  I first noticed this using the [substrate](https://github.com/paritytech/substrate) runtime. I created a small test wasm program to isolate this [here](https://github.com/ChainSafe/gossamer-test-wasm/blob/noot/src/lib.rs#L69). It first calls the external function `ext_set_storage` setting a key-value pair in the trie. Then, it calls another external function `ext_twox_128` which simply hashes some value and returns it. In between these two calls, the value stored in the trie at `key` changes.

### Steps to reproduce

```
git clone https://github.com/ChainSafe/gossamer.git
cd gossamer
git checkout noot/execute-block
go test ./lib/runtime/ -v -run Test_mock_execute_block
```

this will download the test wasm file and call the `mock_execute_block` function that performs the above, in the logs you can see the external function call logs and the trie contents:
```
=== RUN   Test_mock_execute_block
t=2020-06-11T22:02:50-0400 lvl=dbug msg=[NewRuntime] runtimeCtx="{storage:0xc0005b6010 allocator:0xc0001b6280 keystore:0xc0000faaa0}"
t=2020-06-11T22:02:50-0400 lvl=trce msg="[ext_set_storage] executing..."
t=2020-06-11T22:02:50-0400 lvl=trce msg=[ext_set_storage] key=0x4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d val="[0 0 0 0]"
t=2020-06-11T22:02:50-0400 lvl=dbug msg="[teststate] SetStorage" key=0x4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d val=0x00000000
leaf prefix  key 4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d value 00000000

t=2020-06-11T22:02:50-0400 lvl=trce msg="[ext_twox_128] executing..."
t=2020-06-11T22:02:50-0400 lvl=trce msg="[ext_twox_128] hashing..." value=u\r\r"
leaf prefix  key 4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d value 08007500
```

after the first call, the key `4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d` has value `00000000` which is correct. then, after the second call, the value is now `08007500`. 

### Expected behavior

the values stored in the trie stay the same

### Actual behavior

the values changed

### Additional context

let me know if you need any more info - I've tried to isolate the issue, but please let me know if you need me to extract it more. I suspect the issue is something to do with the underlying memory being overwritten or some pointers getting mangled, but I'm not totally sure. maybe there's something I'm missing in the usage of `InstanceContext`.  any help would be much appreciated!

**Comment by AdamSLevy** [comment]
This is due to the issue described in my comment here most likely: 
https://github.com/wasmerio/go-ext-wasm/issues/46#issuecomment-631196119

**Comment by noot** [comment]
@AdamSLevy thanks for pointing that out! I'll take a look and see if I can fix it

**Comment by AdamSLevy** [comment]
It's possible I'm mistaken. Apologies for a red herring.

**Comment by noot** [comment]
no worries! I'll continue to investigate in the meantime.

**Comment by noot** [comment]
@Hywan hey, any updates on the status of this issue? let me know if I can help speed this up in any way.

**Comment by Hywan** [comment]
Sorry, the entire team is busy on a giant secret project. I'll get back to you very soon! Thank you for your patience :-).

**Comment by syrusakbary** [comment]
@Hywan ping on this for next work :)
