### ISSUE TITLE
How to avoid memory corruption?

### ISSUE THREAD

**Issue by AchalaSB** [wasmerio/wasmer-go#136]
I'm working on Linear memory,  I could able to corrupt the memory.
How can I avoid the corruption? ( once the code compiled to wasm, the wasm memory should not corrupt )
What are the precaution I need to consider?

sample code using `string` type
```
#[no_mangle]
pub extern fn greet(subject: *mut c_char) -> *mut c_char {
    let subject_value = unsafe { CStr::from_ptr(subject).to_bytes().to_vec() };
    let mut output = b"Hello ".to_vec();
    output.extend(subject_value);
    output.extend(b" from Wasm!");

    unsafe { CString::from_vec_unchecked(output) }.into_raw()
}
```
go code 
```
	outputLinearMemory := instance.Memory.Data()[outputDataPointer:]
	nth := 0
	var output strings.Builder
	for {
		if outputLinearMemory[nth] == 0 {
			break
		}
		output.WriteByte(outputLinearMemory[nth])
		nth++
	}
	fmt.Println("Processed output:", output.String())

	for i := 0; i < len(outputLinearMemory); i++ {
		outputLinearMemory[i] = 0 // Corrupting the linear memory of the greet function's output
	}
	nth = 0
	var testCorruptionOutput strings.Builder
	for {
		if outputLinearMemory[nth] == 0 {
			break
		}
		testCorruptionOutput.WriteByte(outputLinearMemory[nth])
		nth++
	}
	fmt.Println("Processed output after corruption:", testCorruptionOutput.String())
	fmt.Println("After corrupting Linear memory: ", string(outputLinearMemory))
```
Thanks
cc: @Hywan , @syrusakbary

**Comment by Hywan** [comment]
You're responsible of protecting the access to the memory. Since it's basically a linear buffer, you can write at random positions and corrupts data.

**Comment by AchalaSB** [comment]
Are there any recommended practices to secure the linear memory in this case? 
Please share the materials or docs if you have

**Comment by Hywan** [comment]
I don't have any, I'm sorry. The memory is “shared” being the host and the Wasm instance, so you've to agree on a standard and respect it. Reading memory directly should be less and less frequent with the raise of WIT ([WebAssembly Interface Types](https://github.com/WebAssembly/interface-types)), but it's not there yet (early alpha).
