### ISSUE TITLE
Update to wasmer 0.17.x?

### ISSUE THREAD

**Issue by cohix** [wasmerio/wasmer-go#140]
### Summary

From looking at the PR history here, it seems like this repo is still using older versions of Wasmer (0.14 AFAICT). Are there plans to bring in newer versions of Wasmer?

### Additional details

I have been building a function runner/job scheduler ([Hive](github.com/suborbital/hive)) around wasmer-go, and I plan on doing some additional feature work very soon, just want to make sure everything is as up to date as possible :)

**Comment by syrusakbary** [comment]
Hi @cohix, we are actually working to update to the Wasmer 1.0 alpha (the one in master in the repo).

We just updated the python integration, and the next one in line is Go :)
/ cc @Hywan

**Comment by cohix** [comment]
@syrusakbary thats awesome!! Great to hear. Is there info on the 1.0 alpha anywhere?

**Comment by syrusakbary** [comment]
Not yet, in summary here's what's new in Wasmer 1.0 alpha:
* Refactored compiler architecture, offering up to 5x faster compilation times
* Support for dynamic functions in all compilers
* Support for multivalue, simd in all compilers (except of multivalue in singlepass)
* Error tracing
* Support for headless mode (use a compiled module in a very thin version of Wasmer without any compilers attached)
* Multiarchitecture support (Windows, Mac, Linux, x86_64, arm64, x86, arm32, ...) - note that 32 bit architectures still need to be fully tested

And many more!

**Comment by cohix** [comment]
@syrusakbary very exciting! I would love to help out with the Go ecosystem around wasmer, so if you're looking for help or contributors, let me know!

**Comment by Hywan** [comment]
@cohix Thank you for your help! Please subscribe to the issues and PR, and feel free to help when you've time!
