### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by cohix** [wasmerio/wasmer-go#141]
Thanks for the bug report!

### Describe the bug

Now that the repo and README list the new name for the install command, things are failing. 

### Steps to reproduce

```
> go get github.com/wasmerio/wasmer-go/wasmer
```

If applicable, add a link to a test case (as a zip file or link to a repository we can clone).

### Expected behavior

The install would happen

### Actual behavior

The install fails:
```
module declares its path as: github.com/wasmerio/go-ext-wasm
                but was required as: github.com/wasmerio/wasmer-go
```

### Additional context

Since the latest tagged release (v0.3.1) still has the old name in its go.mod file, go gets confused. Using the latest commit hash (`go get github.com/wasmerio/wasmer-go/wasmer@299b1d478cde6bd5dec4babaa695aeb0ee2cd47a`) works fine.

**Comment by Hywan** [comment]
I'll check about that, thanks for the issue!

**Comment by xzyan** [comment]
Yes i encountered the same problem

```go
> go get -v github.com/wasmerio/wasmer-go
go: github.com/wasmerio/wasmer-go upgrade => v0.3.1
go get: github.com/wasmerio/wasmer-go@v0.3.1: parsing go.mod:
        module declares its path as: github.com/wasmerio/go-ext-wasm
                but was required as: github.com/wasmerio/wasmer-go
```

**Comment by olivierlemasle** [comment]
Could you please create a new tagged release to fix this issue?

**Comment by tomasol** [comment]
The workaround until 1.0.0 is stable seems to be `go get github.com/wasmerio/go-ext-wasm@v0.3.1`
and use import
`wasmer "github.com/wasmerio/go-ext-wasm/wasmer"`

**Comment by jubianchi** [comment]
We now have a [`v1.0.0-beta1`](https://github.com/wasmerio/wasmer-go/releases/tag/v1.0.0-beta1) and new releases are coming soon.

I'm closing this issue and will reopen it if there is any feedback.

**Comment by AndreaEsposit** [comment]
Hey, I still have the same problem, is there a way for me to fix it? 

```
> go get -v github.com/wasmerio/wasmer-go
      go: github.com/wasmerio/wasmer-go upgrade => v0.3.1
      go get: github.com/wasmerio/wasmer-go@v0.3.1: parsing go.mod:
              module declares its path as: github.com/wasmerio/go-ext-wasm
                      but was required as: github.com/wasmerio/wasmer-go
