### ISSUE TITLE
WASI Instance Can not use setContextData

### ISSUE THREAD

**Issue by BruceChoca** [wasmerio/wasmer-go#142]
### Summary

I wrote a demo to test wasi：

```go
module, err := wasm.Compile
wasiVersion := wasm.WasiGetVersion(module)
importObject := wasm.NewDefaultWasiImportObjectForVersion(wasiVersion)
imports, err := wasm.NewImports().Namespace("env").Append("sum", sum, C.sum)
importObject.Extend(*imports)

instance, err := module.InstantiateWithImportObject(importObject)
```

### Additional details

I want use Context：
```go
instance.SetContextData(&contextData)
defer instance.Close()
```

finally，it is error：

```
SIGABRT: abort
PC=0x7fdcca94f18b m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fdcca94f18b
stack: frame={sp:0xc0000096d0, fp:0x0} stack=[0x7ffc5ff82488,0x7ffc607814b0)

runtime: unknown pc 0x7fdcca94f18b
stack: frame={sp:0xc0000096d0, fp:0x0} stack=[0x7ffc5ff82488,0x7ffc607814b0)


goroutine 21 [syscall]:
runtime.cgocall(0x7cf087, 0xc00009fc28, 0x0)
	/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00009fbf0 sp=0xc00009fbb8 pc=0x40796b
github.com/wasmerio/wasmer-go/wasmer._Cfunc_wasmer_instance_destroy(0x168a410)
	_cgo_gotypes.go:809 +0x41 fp=0xc00009fc28 sp=0xc00009fbf0 pc=0x7b1f51
github.com/wasmerio/wasmer-go/wasmer.cWasmerInstanceDestroy(0x168a410)
```

What's the reason？
Doesn't wasi support contextdata？
What should i do if i want to use contextdata at wasi ？

**Comment by Hywan** [comment]
Hey,

What your context data looks like?
Note: This project is being rewritten from scratch to provide a better and more powerful API.

**Comment by BruceChoca** [comment]
> Hey,
> 
> What your context data looks like?
> Note: This project is being rewritten from scratch to provide a better and more powerful API.
 
I am developing a project that needs to use this feature, 
I hope to be able to solve this problem, thank you

**Comment by Hywan** [comment]
Hello,

`wasmer-go` 1.0 is about to be released in a couple of days. The `SetContextData` function has been removed. See #183.
