### ISSUE TITLE
Possibility on implementing (de)alloc on host side

### ISSUE THREAD

**Issue by C0MM4ND** [wasmerio/wasmer-go#144]
### Summary

I see that when the host side passing a str/bytes to the wasm, we need to alloc and copy data on the new mem part, like [the greet example](https://github.com/wasmerio/wasmer-go/blob/299b1d478cde6bd5dec4babaa695aeb0ee2cd47a/wasmer/example_greet_test.go).

However the (de)alloc func is written on the wasm modules, which means every wasm module writer has to write two before coding a wasm lib, and every host writer has to emphasize this.

So I wanna ask that is it possible that to implementing (de)alloc purely on server side, hidden from the wasm module writer. Or any proposal about this?

### Additional details

I have tried using Memory.Grow to add the string to the new page, which is a waste on physical mem especially when the str length far less than the page size (64ki)

**Comment by Hywan** [comment]
Hello,

It is possible to import a `malloc` and a `free` functions inside the Wasm module, and let host functions (imported functions) on the host-side be the implementation. Something like this:

```wat
(module
  (import "env" "malloc" (func (param i32 i32) (result i32)))
  …)
```

on the Go side, something like this:

```go
importObject.Register(
	"env",
	map[string]wasmer.IntoExtern{
		"malloc": wasmer.NewFunction(
			store,
			wasmer.NewFunctionType(wasmer.NewValueTypes(wasmer.I32, wasmer.I32), wasmer.NewValueTypes(wasmer.I32)),
			func(args []wasmer.Value) ([]wasmer.Value, error) {
				// doing an allocation, and getting a pointer to it
				return []wasmer.Value{wasmer.NewI32(pointer)}, nil
			},
		),
	},
)

instance, err := wasmer.NewInstance(module, importObject)
```

This code is not tested, I just wrote it directly on Github.
