### ISSUE TITLE
please update the Example_greet example with the master code

### ISSUE THREAD

**Issue by zonghaishang** [wasmerio/wasmer-go#146]
Thanks for proposing a new feature!

### Motivation

A clear and concise description of what the motivation for the new feature is, and what problem it is solving.

### Proposed solution

A clear and concise description of the feature you would like to add, and how it solves the motivating problem.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

### Additional context

![image](https://user-images.githubusercontent.com/15549777/98134818-1cdf8500-1efa-11eb-8550-0d11a536c073.png)

**Comment by jubianchi** [comment]
Hi @zonghaishang!

This is actually a work in progress, see #145.

**Comment by zonghaishang** [comment]
@jubianchi 
Thanks for the reply, can you add a demonstration of calling wasm plugin in the host, for example, the host needs to call the wasm plugin go method:

```
// wasm plugin method
func Greet(name string) string
```

Based on the master code, a bit confused:

1. How to parse the string parameters passed by host in the wasm plugin
2. How to pase the return value on the host

I am just new to wasm-go, I hope to give some guidance, thanks again.
I am currently writing a demo program for calling the wasm plug-in with go, but I currently encounter a lot of resistance.

**Comment by Hywan** [comment]
The project is under rewrite. The `master` branch is working but probably not stable. The documentation and the examples are currently under a large rewrite. Please be patient for a couple of days :-).

**Comment by peter-mogensen** [comment]
Maybe add that statement in the top of the master README file?
