### ISSUE TITLE
Memory leak in instance creation

### ISSUE THREAD

**Issue by koponen-styra** [wasmerio/wasmer-go#148]
Thanks for the bug report!

### Describe the bug

Releasing the instance doesn't free all memory.

### Steps to reproduce

1. Run the following:

```package main

import (
        "github.com/wasmerio/wasmer-go/wasmer"
        "runtime"
)

func main() {
        for {
                instance()
        }
}

func instance() {
        wasmBytes := []byte(`
                (module
                  (type $add_one_t (func (param i32) (result i32)))
                  (func $add_one_f (type $add_one_t) (param $value i32) (result i32)
                    local.get $value
                    i32.const 1
                    i32.add)
                  (export "add_one" (func $add_one_f)))
        `)

        engine := wasmer.NewEngine()
        store := wasmer.NewStore(engine)
        module, err := wasmer.NewModule(store, wasmBytes)
        if err != nil {
                panic(err)
        }

        importObject := wasmer.NewImportObject()
        _, err = wasmer.NewInstance(module, importObject)
        if err != nil {
                panic(err)
        }

        runtime.GC()
} 
```

2. See the process memory usage to increase and eventually the process crashing to "Cannot allocate memory".

Additional context:

Uncommenting the commented out SetFinalizer call (with TODO note) in import_object.go has no effect.

**Comment by jubianchi** [comment]
Hi @koponen-styra, thanks for reporting this!

I can confirm the leak here.

We are currently looking at memory leaks on Wasmer. The one you are experiencing does not come from Go but from the Rust part.

**Comment by syrusakbary** [comment]
Small update: we already have a quick fix for the memory leak and we are doing a deep research to find more!

https://github.com/wasmerio/wasmer/pull/1822

**Comment by koponen-styra** [comment]
> Small update: we already have a quick fix for the memory leak and we are doing a deep research to find more!
> 
> [wasmerio/wasmer#1822](https://github.com/wasmerio/wasmer/pull/1822)

Great!

**Comment by syrusakbary** [comment]
We merged the mentioned PR, and now are solving a small leak when using exports in instances. It should be upstream soon!

**Comment by syrusakbary** [comment]
We have a PR in progress that solves all the observed memory leaks:

https://github.com/wasmerio/wasmer/pull/1837#issuecomment-733063061

```
==92344== LEAK SUMMARY:
==92344==    definitely lost: 0 bytes in 0 blocks
==92344==    indirectly lost: 0 bytes in 0 blocks
==92344==      possibly lost: 0 bytes in 0 blocks
==92344==    still reachable: 68,961 bytes in 178 blocks
==92344==         suppressed: 15,633 bytes in 163 blocks
```

**Comment by jubianchi** [comment]
Hi @koponen-styra!

Some updates here: `beta1` of Wasmer is out and it fixes many (most of) the leaks.

The release for `wasmer-go` will follow shortly. If you want to give it a try before it's out, have a look at #153.

**Comment by jubianchi** [comment]
I'm closing this issue for now as our tests did not reveal any leak actually.

Feel free to reopen if needed.
