### ISSUE TITLE
Does not build with gcc

### ISSUE THREAD

**Issue by olivierlemasle** [wasmerio/wasmer-go#149]
### Describe the bug

On master, `wasmer-go` builds only with CLANG, not with gcc

### Steps to reproduce

1. Clone master (currently dfca9ab0)
1. Try building with gcc:
   ```
   $ CC=gcc go build ./...
   # github.com/wasmerio/wasmer-go/wasmer
   /usr/bin/ld: $WORK/b001/_cgo_main.o:/tmp/go-build/cgo-generated-wrappers:8: undefined reference to `wasm_limits_max_default'
   collect2: error: ld returned 1 exit status
   ```

1. Build with clang:
   ```
   CC=clang go build ./...
   ```

### Expected behavior

I expect wasmer-go to build with both gcc and clang, or at least with gcc (because it's currently documented [here][https://github.com/wasmerio/wasmer-go#install).

### Actual behavior

See error above: `undefined reference to 'wasm_limits_max_default'`

### Additional context

- OS : Fedora 33
- Go version : `go version go1.15.2 linux/amd64`
- <details>
  <summary>go env</summary>

	```
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/vscode/.cache/go-build"
	GOENV="/home/vscode/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/go"
	GOPRIVATE=""
	GOPROXY="direct"
	GOROOT="/usr/lib/golang"
	GOSUMDB="off"
	GOTMPDIR=""
	GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/workspaces/wasmer-go/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build788586221=/tmp/go-build -gno-record-gcc-switches"
	```
	</details>

**Comment by jubianchi** [comment]
Hi @olivierlemasle thanks for reporting that!

Actually, `cgo` and `gcc` are causing this problem. See : 
* https://github.com/golang/go/issues/40820
* https://github.com/golang/go/issues/39136

So for now, the only option is to build with `clang`.

Another option might be to report this issue to https://github.com/WebAssembly/wasm-c-api. Thoughts @nlewycky @MarkMcCaskey @Hywan?

**Comment by Hywan** [comment]
We must report the issue to the Wasm C API Working Group. We can't keep gcc users away.

**Comment by qmuntal** [comment]
I don´t expect Go to fix this in the near future, as it is a tricky issue that has been opened for more than two years.

Meanwhile it is not fixed, if possible, in Wasm C API a possible workaround is to comment or remove `static const uint32_t wasm_limits_max_default = 0xffffffff;` and define `const LimitMaxUnbound = uint32(0xffffffff)` instead of `const LimitMaxUnbound = uint32(C.wasm_limits_max_default)`. I´ve validated this approach locally and works as expected.
