### ISSUE TITLE
Error undefined reference to `wasm_limits_max_default' when trying to run a wasm file.

### ISSUE THREAD

**Issue by krasi-georgiev** [wasmerio/wasmer-go#160]
Happens when I run the program below with the attached file.

```
package main

import (
	"io/ioutil"
	"log"

	"github.com/wasmerio/wasmer-go/wasmer"
)

func main() {
	wasmBytes, err := ioutil.ReadFile("edge-impulse-standalone.wasm")
	if err != nil {
		log.Fatal(err)
	}

	engine := wasmer.NewEngine()
	store := wasmer.NewStore(engine)

	// Compiles the module
	module, err := wasmer.NewModule(store, wasmBytes)
	if err != nil {
		log.Fatal(err)
	}

	// Instantiates the module
	importObject := wasmer.NewImportObject()
	instance, err := wasmer.NewInstance(module, importObject)
	if err != nil {
		log.Fatal(err)
	}

	run_classifier, err := instance.Exports.GetFunction("run_classifier")
	if err != nil {
		log.Fatal(err)
	}

	result, _ := run_classifier(5, 37)
}
```

[edge-impulse-standalone.wasm.zip](https://github.com/wasmerio/wasmer-go/files/5688052/edge-impulse-standalone.wasm.zip)

**Comment by jubianchi** [comment]
Hello @krasi-georgiev!

This is actually a known issue and it has been fixed in https://github.com/wasmerio/wasmer-go/pull/156 but not released yet.

For reference, you can have a look at https://github.com/wasmerio/wasmer-go/issues/149

**Comment by krasi-georgiev** [comment]
Thanks , I just tried latest and indeed this error is resolved, I am not getting another error and opened a mother issue
https://github.com/wasmerio/wasmer-go/issues/161
