### ISSUE TITLE
Missing import: `env`.`_embind_register_memory_view` when running a wasm file.

### ISSUE THREAD

**Issue by krasi-georgiev** [wasmerio/wasmer-go#161]
Running the following program results in an error: `Missing import: `env`.`_embind_register_memory_view``

[edge-impulse-standalone.wasm.zip](https://github.com/wasmerio/wasmer-go/files/5688238/edge-impulse-standalone.wasm.zip)

```
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"github.com/wasmerio/wasmer-go/wasmer"
)

func main() {
	wasmBytes, err := ioutil.ReadFile("edge-impulse-standalone.wasm")
	if err != nil {
		log.Fatal(err)
	}

	engine := wasmer.NewEngine()
	store := wasmer.NewStore(engine)

	// Compiles the module
	module, err := wasmer.NewModule(store, wasmBytes)
	if err != nil {
		log.Fatal(err)
	}

	// Instantiates the module
	importObject := wasmer.NewImportObject()
	instance, err := wasmer.NewInstance(module, importObject)
	if err != nil {
		log.Fatal(err)
	}

	run_classifier, err := instance.Exports.GetFunction("run_classifier")
	if err != nil {
		log.Fatal(err)
	}

	result, _ := run_classifier(5, 37)
	fmt.Println(result)
}

```

**Comment by Hywan** [comment]
Hello,

The error means that an import is missing. I guess the compiler that has been used to compile this Wasm file adds a specific set of required imports. Do you know what compiler has been used?

**Comment by krasi-georgiev** [comment]
passing along the answer from the wasm devs - `embind` was used and now he will try to use `wasienv`

**Comment by krasi-georgiev** [comment]
here is an update the wasm devs managed to generate the wasm file using [wasienv](https://docs.wasmer.io/ecosystem/wasienv/getting-started) and the file now runs fine with `wasmer` , but go still returns an error - ` Missing import: 'wasi_unstable'.'fd_prestat_get'`

Attached the wasm file with the makefile that generated it.

[example-standalone-inferencing.zip](https://github.com/wasmerio/wasmer-go/files/5690068/example-standalone-inferencing.zip)

**Comment by Hywan** [comment]
OK, this error means that WASI is required. The rewrite of Go doesn't contain WASI *yet*, we are working on it, it's going to land soon.

**Comment by krasi-georgiev** [comment]
Thanks for the prompt reply
