### ISSUE TITLE
Apple M1 ARM support

### ISSUE THREAD

**Issue by BruceChoca** [wasmerio/wasmer-go#167]
Hi All，Do you have plans to support Apple M1 ARM ？

**Comment by jubianchi** [comment]
Hello @BruceChoca!

Now that Wasmer is released with M1 support we'll work on extending support for M1 on wasmer related projects.

We'll track progress in this issue.

**Comment by syrusakbary** [comment]
I think this feature just depends on Go supporting Apple M1 ARM, once that happens everything should work I believe!

**Comment by BruceChoca** [comment]
@jubianchi  that is good, thank u very much
Now, there are still some errors in GO 1.16.1beta darwin-amd64

**Comment by Hywan** [comment]
It works on my M1 machine, but we need Go 1.16beta1, and a custom Wasmer (Rust runtime, the original One) build. That's OK, but we can't produce them automatically for the moment. Time is our friend :-).

**Comment by BruceChoca** [comment]
ok, I got it, thank u very much

**Comment by karelbilek** [comment]
hello. Is this.. still in progress? Rust wasmer does not support M1/M2 in 2023?

**Comment by syrusakbary** [comment]
Rust Wasmer has been supporting M1/M2 since a few months after it launched.
I believe the only pending thing is updating the libraries in wasmer-go :)

**Comment by karelbilek** [comment]
I see there _is_ some library here?

https://github.com/wasmerio/wasmer-go/commit/8c6ce3e91d596585642ead0dcf05d31860848c3a

I am not sure if that's the library you mean (I don't fully understand WASM/WASI/wasmer ... yet :D I will look into it though)

**Comment by karelbilek** [comment]
Anyway yeah it runs fine on my M1 machine. I... think this can be closed and the readme updated?
