### ISSUE TITLE
Close gap with CLI

### ISSUE THREAD

**Issue by tiborvass** [wasmerio/wasmer-go#17]
This may be a meta issue, it's not specific to the Go bindings (feel free to close/move the issue), but I'm opening it here since I'd be using the Go bindings.

### Motivation

Users expect to be able to do the same things from the Go code than from the wasmer CLI.
Very concretely I need --mapdir and --env (https://github.com/wasmerio/wasmer/issues/475).

### Proposed solution

Tediously implement all new CLI features in all the bindings.

### Alternatives

Generate an `Options` struct that would be passed as a parameter to a NewInstance() constructor. The struct could be generated from a simple struct definition in the wasmer repo.

**Comment by Hywan** [comment]
Thanks for the proposal. I'm not sure we can reflect all the wasmer CLI options with the current C/C++ bindings, but it's totally achievable.

Let's keep this issue open and let's address one feature at a time!

**Comment by Hywan** [comment]
The CLI has been removed as we prefer to keep `wasmer-go` as a library. Closing this issue :-).
