### ISSUE TITLE
WASI in v1.0.0

### ISSUE THREAD

**Issue by cohix** [wasmerio/wasmer-go#171]
### Summary

I can't see anything in the docs or source that would let me use WASI imports with the 1.0.0-x releases. Is this something that's going to be re-added? It's preventing me from upgrading to newer versions.

Cheers

**Comment by syrusakbary** [comment]
Yeah, we are working on that right now! (and it's the main reason we haven't created the `1.0.0` final version in wasmer-go yet)

cc @Hywan @jubianchi

**Comment by cohix** [comment]
Well that's great! Can't wait :) I'd like to leave this open until it's available, if that's alright? Would be good to get a notification so I can jump on the upgrade.

**Comment by Hywan** [comment]
It's OK to keep this issue open for the moment :-).
