### ISSUE TITLE
Link to example program in Readme is broken

### ISSUE THREAD

**Issue by daniel-garcia** [wasmerio/wasmer-go#172]
### Describe the bug

The project readme includes an example:
https://github.com/wasmerio/wasmer-go#basic-example-exported-function

In that section there is a link to download an example program.

https://github.com/wasmerio/wasmer-go/blob/master/wasmer/test/testdata/examples/simple.wasm

The link is broken.

### Steps to reproduce

1. Navigate to https://github.com/wasmerio/wasmer-go#basic-example-exported-function
2. click on link to simple.wasm
3. See 404

### Expected behavior

The example should reference a valid link or include enough data to allow the user to generate that file.

### Actual behavior

Broken link and user must reference instructions not found on-site to make the example work.

**Comment by jubianchi** [comment]
Hi @daniel-garcia!

Thanks for reporting this issue. I'll fix that today.

**Comment by Hywan** [comment]
Fixed.
