### ISSUE TITLE
Is it possible to access wasmer instance in import function?

### ISSUE THREAD

**Issue by antJack** [wasmerio/wasmer-go#173]
In version 0.3, we could access the wasmer instance in import function through SetContextData() and IntoInstanceContext(context), but how can we do that in version 1.0?

```go
hostFunction := wasmer.NewFunction(
	store,
	wasmer.NewFunctionType(wasmer.NewValueTypes(), wasmer.NewValueTypes(wasmer.I32)),
	func(args []wasmer.Value) ([]wasmer.Value, error) {
		//
		//	is it possible to access wasmer instance here?
                //      for example, one may wish to get some bytes from instance's memory
		//
		return []wasmer.Value{wasmer.NewI32(0)}, nil
	},
)

importObject := wasmer.NewImportObject()
importObject.Register(
	"",	
	map[string]wasmer.IntoExtern{
		"host_function": hostFunction,
	},
)

instance, err := wasmer.NewInstance(module, importObject)
```

**Comment by Hywan** [comment]
Didn't try yet, but you may be able to define an `instance` variable, bind it inside your closure, and re-define a value for `instance` when doing `wasmer.NewInstance`. Thoughts?

**Comment by Hywan** [comment]
Note, that's something we could quite easily add: Injecting the current instance as the first argument of the host function.

**Comment by antJack** [comment]
Thanks for replying, but consider the case that multiple instances were created and called the hostFunction concurrently
Moreover, unfortunately, the hostFunction should conform to API spec, and therefore impossible to inject any arguments

**Comment by Hywan** [comment]
You're right. Then I think we must handle that as a new feature :-).

**Comment by Hywan** [comment]
So the solution is to use a host function environment. In Go-pseudo-code-ish:

```go
// Let's declare a host function environment
type MyEnvironment struct {
	instance *wasmer.Instance,
	theAnswer int32,
}

environment := &MyEnvironment {
	instance: nil,
	theAnswer: 42,
}

// Let's use it in a host function!
function := wasmer.NewFunctionWithEnvironment(
	store,
	wasmer.NewFunctionType(wasmer.NewValueTypes(I32, I32), wasmer.NewValueTypes(I32)),
	environment,
	func(environment interface{}, args []wasmer.Value) ([]wasmer.Value, error) {
		// Get back the environment!
		env := environment.(*MyEnvironment)
		…
	},
)

// Let's create the import object, as usual.
importObject := NewImportObject()
importObject.Register(
	"env",
	map[string]wasmer.IntoExtern{
		"foo": function
	},
)

// And now, the instance.
instance, _ := wasmer.NewInstance(module, importObject)

// Finally, let's update the environment.
environment.instance = instance
```

I believe it should work.

**Comment by Hywan** [comment]
Closing for the same reason as in https://github.com/wasmerio/wasmer/issues/2023#issuecomment-779070808. Feel free to reopen if any questions pop :-).
