### ISSUE TITLE
can you provide a example about cgo to make wasm. 

### ISSUE THREAD

**Issue by izouxv** [wasmerio/wasmer-go#179]
### Summary

A clear and concise summary of your question.

### Additional details

Provide any additional details here.

**Comment by Hywan** [comment]
Hello,

I don't understand your question. Can you reformulate please?

**Comment by Hywan** [comment]
This project helps to run Wasm inside Go.
This project _does not_ compile Go to Wasm.

I'm closing the issue. Feel free to reopen if you have more questions, I'll be happy to help.
