### ISSUE TITLE
Global and Memory imports

### ISSUE THREAD

**Issue by yyh1102** [wasmerio/wasmer-go#19]
Thanks for proposing a new feature!

### Motivation

How can i import `global` and `memory` from Go side when executing wasm bytecode? It's a feature in need when implementing smart contract virtual machine~

**Comment by Hywan** [comment]
Thanks for the proposal. It's not possible yet, but I can work on it. Will do this as soon as possible.

**Comment by jubianchi** [comment]
I'm closing this issue as the feature has been implemented as part of the the rewrite.

@yyh1102 you can have a look at [this example](https://github.com/wasmerio/wasmer-go/blob/examples/examples/example_imports_exports_test.go) (which is part of a #145)
