### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kaimast** [wasmerio/wasmer-go#196]
I am quite new to Go, so I might be doing something that is obviously wrong here, but would appreciate any help.

I installed wasmer-go like described in the readme
```
 go get github.com/wasmerio/wasmer-go/wasmer 
```

Now when I want to use it in my project I get the following error:
```
vendor/github.com/wasmerio/wasmer-go/wasmer/cgo.go:12:11: fatal error: wasmer_wasm.h: No such file or directory
   12 | // #include <wasmer_wasm.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:26: ol] Error 2
````

Any idea what this could be caused by?

**Comment by Hywan** [comment]
Hello,

* Do you have `cgo` installed?
* What's your OS, or architecture?

**Comment by Hywan** [comment]
Did you run something like `go mod vendor`?

**Comment by Hywan** [comment]
It seems to be the same error as https://github.com/golang/go/issues/29479 or https://github.com/golang/go/issues/26366. Looking.

**Comment by Hywan** [comment]
So, when running `go mod vendor`, the `packaged/` directory isn't copied because it contains no `.go` file. I'm fixing that.

**Comment by kaimast** [comment]
I did run `go mod vendor`. Thanks for looking into this!

Right now I just got rid of `src/vendor` and the `mod vendor` command in my workflow to get it to work.
