### ISSUE TITLE
panic: Missing import: `env`.`syscall/js.valueGet`

### ISSUE THREAD

**Issue by zhengzepeng** [wasmerio/wasmer-go#214]
### Summary
```
panic: Missing import: `env`.`syscall/js.valueGet`
```
### Additional details

1、Use tinygo to compile the wasm,code like that:
```
package main

import "context"

// This calls a JS function from Go.
func main() {
	println(context.Background())
	println("result : ", multiply(2, 3)) // expecting 5
}

// This function is exported to JavaScript, so can be called using
// exports.multiply() in JavaScript.
//export multiply
func multiply(x, y int) int {
	return x * y
}
```
and compile：
```
tinygo build -o wasm.wasm -target wasm ./wasm.go
```
the output file is `wasm.wasm`
2、use this lib to load and run the wasm

```
package main

import (
	"fmt"
	wasmer "github.com/wasmerio/wasmer-go/wasmer"
	"io/ioutil"
)

func main() {
	LoadTinyGo()
}

func LoadTinyGo() {
	wasmBytes, _ := ioutil.ReadFile("wasmdemo2/wasmsource/wasm.wasm")

	engine := wasmer.NewEngine()
	store := wasmer.NewStore(engine)

	// Compiles the module
	module, _ := wasmer.NewModule(store, wasmBytes)

	// Instantiates the module
	env, err := wasmer.NewWasiStateBuilder("Demo").Finalize()
	if err != nil {
		panic(err)
	}
	importObject, err := env.GenerateImportObject(store, module)
	if err != nil {
		panic(err)
	}
	instance, err := wasmer.NewInstance(module, importObject)
	if err != nil {
		panic(err)
	}

	// Gets the `multiply` exported function from the WebAssembly instance.
	multiply, _ := instance.Exports.GetFunction("multiply")

	// Calls that exported function with Go standard values. The WebAssembly
	// types are inferred and values are casted automatically.
	result, _ := multiply(50, 370)

	fmt.Println(result) // 18500!
}
```

Unfortunately, there was a mistake：
```
panic: Missing import: `env`.`syscall/js.valueGet`

goroutine 1 [running]:
main.LoadTinyGo()
        /go/src/zhengzepeng/example/wasmdemo2/simple.go:33 +0x269
main.main()
        /go/src/zhengzepeng/example/wasmdemo2/simple.go:10 +0x25

```

3、simple the wasm code，like that:

```
package main

// This calls a JS function from Go.
func main() {
	println("result : ", multiply(2, 3)) // expecting 5
}

// This function is exported to JavaScript, so can be called using
// exports.multiply() in JavaScript.
//export multiply
func multiply(x, y int) int {
	return x * y
}
```

i didnt use the context , and compile it again.
```
tinygo build -o wasm.wasm -target wasm ./wasm.go
```
the output file is `wasm.wasm`

Finally repeat step 2，and it run ok.

So it confuse me，the only difference between step one and step three is step one use the context,and step three didnt use the context. Can any one help?

**Comment by Hywan** [comment]
Hello,

The problem doesn't come from `wasmer-go` nor your code. Tinygo unfortunately generates a Wasm module that aims to work in a browser _only_ and thus expects host functions defined in JS.

Those JS host functions are defined in `$GOROOT/misc/wasm/wasm_exec.js`, and we see the `syscall/js.valueGet` implementation:

https://github.com/golang/go/blob/0f66fb7b856b02497cf801ce72d80f375f53358b/misc/wasm/wasm_exec.js#L361-L366

The Wasm support in Go is still experimental and limited to Web usage only. It explains why a JS API is required by the Wasm module.

**Comment by Hywan** [comment]
See #95 to see a more in-depth discussion.

**Comment by zhengzepeng** [comment]
> See #95 to see a more in-depth discussion.

I try to use the go-wasm-adapter，and it doesn't work now. Anyway，thanks to reply，hope it fits soon and can't wait to use wasmer-go on golang

**Comment by Hywan** [comment]
There is this discussion to update go-wasm-adapter to wasmer-go 1.0. Closing this issue :-).
