### ISSUE TITLE
Ability to pause, save state and restore VM

### ISSUE THREAD

**Issue by dobegor** [wasmerio/wasmer-go#22]
### Motivation

With ability to pause the VM, save it's state (memory, execution context) and restore it later
it'd be possible to created sandboxed environments with ability to migrate them.

**Comment by Hywan** [comment]
Thanks for the interesting proposal! I suggest you to fill the same issue on https://github.com/wasmerio/wasmer since it heavily relies on the WebAssembly runtime.

**Comment by gedw99** [comment]
Looking forward to this.
It's great how flexible wasi can be in this regards. Shiftable workloads.

**Comment by Hywan** [comment]
It's under development https://github.com/wasmerio/wasmer/pull/489.

**Comment by artjoma** [comment]
Any news about this functionality ?

**Comment by Hywan** [comment]
Not yet. It's not a feature that is part of wasmerio/wasmer for the moment :-).

**Comment by Hywan** [comment]
Closing this issue in favor of https://github.com/wasmerio/wasmer/issues/480 :-).
