### ISSUE TITLE
How to use LLVM backend

### ISSUE THREAD

**Issue by hanabi1224** [wasmerio/wasmer-go#222]
> Important: Please note that we only recommend Cranelift for development proposes, for production we recommend using LLVM

As per https://github.com/wasmerio/wasmer/issues/142  LLVM backend is recommended, however, I could not get it working out of box, below code prints false. Any guidance on that? Do I need some extra environment setting or manually re-compile the lib with llvm feature? Thanks!
```go
available := wasmer.IsCompilerAvailable(wasmer.LLVM)
fmt.Println(available)
```

**Comment by Hywan** [comment]
LLVM isn't part of the default `libwasmer` that we provide _yet_. We have some issues on Windows with it for example. We are working on it though.

In the meantime, you can build your own custom Wasmer library. See https://github.com/wasmerio/wasmer-go#supported-platforms:

```sh
$ # Build the new Wasmer C API shared object library.
$ cargo build --release
$
$ # Configure cgo.
$ export CGO_CFLAGS="-I$(pwd)/wasmer/packaged/include/"
$ export CGO_LDFLAGS="-Wl,-rpath,$(pwd)/target/release/ -L$(pwd)/target/release/ -lwasmer_go"
$
$ # Run the tests.
$ just test -tags custom_wasmer_runtime
```

**Comment by hanabi1224** [comment]
@Hywan Awesome, thanks for your quick response!

**Comment by Hywan** [comment]
You're welcome :-).
