### ISSUE TITLE
Can I run an already compiled wasm module?

### ISSUE THREAD

**Issue by Gaboose** [wasmerio/wasmer-go#238]
### Summary

I have a `hello_world.wasm` module with wasi interface that I can successfully run like this:
```
$ wasmer run hello_world.wasm
Hello, world!
```

Is there a way to run it with wasmer-go? As far as I can tell the `wasmer.NewModule` method takes a wasm module as a byte array of WAT code as argument, and I can't find any example that would use a wasm module that's already compiled.

## Additional details

I looked at:
- https://pkg.go.dev/github.com/wasmerio/wasmer-go/wasmer
- https://github.com/wasmerio/wasmer-go/tree/master/examples

**Comment by Hywan** [comment]
Sure,

You can use the `Module.Serialize`and `Module.Deserialize` API. They have been designed specifically for that (https://pkg.go.dev/github.com/wasmerio/wasmer-go/wasmer#Module.Serialize).

**Comment by Hywan** [comment]
Closing as I believe the question has been answered. Feel free to re-open if you need more information :-).
