### ISSUE TITLE
Can we still use sth equivalent to `instance.Memory.Data()`?

### ISSUE THREAD

**Issue by joehattori** [wasmerio/wasmer-go#243]
I've just started playing with wasmer recently, and have a question.
As in [this example in v.0.3](https://github.com/wasmerio/wasmer-go/blob/75326bf847202945964e09905ecf64bd9d1baeee/wasmer/example_greet_test.go#L45), `instance.Memory.Data()` looks pretty useful. Does this feature still exist in the current version? If not, what would be an appropriate way to implement the test above?
Thanks!

**Comment by Hywan** [comment]
Hello,

Yes this function exists in the 1.0.* version, see [`Memory.Data`](https://pkg.go.dev/github.com/wasmerio/wasmer-go/wasmer#Memory.Data) :-).

**Comment by joehattori** [comment]
@Hywan Thank you for replying!
Is there any way to get the whole memory of the instance like `instance.Memory` in v1.0.*?
I just thought it would be nice to be able to get the desired data of the memory by providing the offset as in the [example above](https://github.com/wasmerio/wasmer-go/blob/75326bf847202945964e09905ecf64bd9d1baeee/wasmer/example_greet_test.go#L45).
If `instance.Memory` doesn't exist, do we have to export memory explicitly with name each time and use `instance.Exports.GetMemory(name)` to access it?

**Comment by joehattori** [comment]
@Hywan Thank you for your quick reply.
It turned out I didn't know that memory is by default exported from Rust modules under the name "memory".
Question resolved, closing this issue👍
