### ISSUE TITLE
Dynamic function returned wrong signature. Expected [I32] but got [I64]

### ISSUE THREAD

**Issue by prep** [wasmerio/wasmer-go#260]
### Describe the bug
When compiling a wasm module with TinyGo, depending on the packages that is Imported I can either successfully call the `_start()` function or I get the following error:

```
Dynamic function returned wrong signature. Expected [I32] but got [I64]
```

### Steps to reproduce

I've made an example of the issue available at [prep/wasmer-example](https://github.com/prep/wasmer-example).

### Expected behavior

I expect to successfully call `_start()` regardless of my imports.

### Actual behavior

When my wasm module imports `fmt`, I get the stated error returned.

### Additional context

I'm not actually sure if this is a bug in wasmer or in Go/TinyGo.

As you can see I've made [dummy imports](https://github.com/prep/wasmer-example/blob/master/cmd/runtime/imports.go) to satisfy the `syscall/js` package. I don't expect these having an effect on the described bug, but nonetheless wanted to mention it.

**Comment by Hywan** [comment]
Hello,

Thank you for the detailed bug report!

`tinygo` has 2 WebAssembly targets: `wasm` and `wasi`. If you use the `wasi` target, the `_start` function will be compiled correctly, and everything will work as expected :-).

**Comment by prep** [comment]
Hey Ivan!

You are absolutely correct. It's something I found out as well while testing over the weekend and I should have updated this ticket accordingly. However, I still managed to break it quite easily as [example3.go](https://github.com/prep/wasmer-example/blob/master/example3.go) shows in my repo. This resulting error is the same.

There is probably a relationship with `reflect` and `interface` types, as changing the `err` field to a `string` type doesn't trigger the error. I see the same problem when calling function A, that calls function B with a `struct` that contains an `interface` field.

Having said all that, I'm not sure if this is really a wasmer problem and could be more of a TinyGo problem to be honest, although I wouldn't mind hearing your thoughts on this 😉

**Comment by prep** [comment]
More testing confirmed that this is indeed a TinyGo problem.

**Comment by Hywan** [comment]
If you open a bug report on TinyGo's repository, please link to this issue, so that I can keep track of it :-). Thanks!

**Comment by prep** [comment]
I won't open a bug report, because I'm not sure it's helpful at the moment. The error pops up whenever the wasm module compiled by TinyGo panics for whatever reason.

For example, if I write to a `map` that is `nil` then that's a panic and wasmer returns the `Expected [I32] but got [I64]` error. This is of course my fault and not the fault of wasmer or TinyGo.

Then there is the `fmt.Sprintf("%#v", MyStruct{})` example where `MyStruct{}` has an `interface` field. This panics because TinyGo's `reflect` package is still [missing some stuff](https://github.com/tinygo-org/tinygo/blob/release/src/reflect/value.go#L374). So this is not so much a bug as it is a partial implementation which I can imagine they're more than aware of 😉
