### ISSUE TITLE
2.0 release being tagged soon?

### ISSUE THREAD

**Issue by cohix** [wasmerio/wasmer-go#289]
### Summary

@Hywan curious what the timeline is for tagging 2.0? I see some related PRs have been merged so hopefully soon :)

### Additional details

In particular hoping to get easy support for M1 Macs and all the underlying 2.0 goodness :)

**Comment by Hywan** [comment]
I wanted to support Windows, so to close #200, but my time for this project is currently a little bit low (for a couple of weeks). If that's important for you, we can update our agenda to make a new release for sure!

cc @syrusakbary

**Comment by cohix** [comment]
@Hywan A new tag would be much appreciated :)

**Comment by Hywan** [comment]
[v1.0.4](https://github.com/wasmerio/wasmer-go/releases/tag/v1.0.4) just released :-).

**Comment by cohix** [comment]
🥳
