### ISSUE TITLE
Make `GetLastError` threadsafe

### ISSUE THREAD

**Issue by AdamSLevy** [wasmerio/wasmer-go#96]
### Summary

If I am running multiple independent wasmer instances concurrently in separate goroutines, can those goroutines safely call `wasmer.GetLastError()` and trust that they will return the error relevant to their local instance?

For example, say I have multiple goroutine's doing the following. Can errStr be relied on?
```
func runWasm() {
    // load a Module from some wasm called mod
...

    i, _ := mod.Instantiate()
    v, err := i.Exports["run"]
    if err != nil {
        errStr, _ := wasmer.GetLastError()
        panic(errStr)
    }
    ...
}
```

**Comment by Hywan** [comment]
Good question.

In `wasmer-runtime-c-api`, it is thread-safe:

https://github.com/wasmerio/wasmer/blob/71b342e5b1348b310d96266dfdff7a7bcd76c159/lib/runtime-c-api/src/error.rs#L10-L12

However, on the Go side, I'm not sure it is. Asking @bjfish or @losfair to confirm.

**Comment by AdamSLevy** [comment]
After re-reading both the C and the Go code I am now 90% confident that this is threadsafe. I would still love to hear that confirmed from other devs.

**Comment by Hywan** [comment]
After a discussion with @losfair, it appears it's not totally safe from the Go side. We must fix it by adding https://golang.org/pkg/runtime/#LockOSThread around `GetLastError` inside the code.

**Comment by AdamSLevy** [comment]
Thanks for the update. Just off the top fo my head I'm a little concerned that LockOSThread may need to be called back before the Wasm runtime error occurs, i.e. before the Wasm function is called.

**Comment by AdamSLevy** [comment]
@losfair @Hywan if you can comment on my concern and let me know how this should be properly implemented I will happily submit a PR to that end.

**Comment by losfair** [comment]
@AdamSLevy Yeah, `LockOSThread` needs to be called before the Wasm function to ensure that `GetLastError` executes on the same thread the error occurred on.

We might refactor error handling a bit and do `GetLastError` internally so that public API users do not need to deal with locking OS threads. For now however, a workaround would be:

```go
runtime.LockOSThread()
callSomeFunctionOnInstance()
err := wasmer.GetLastError()
runtime.UnlockOSThread()
```

**Comment by AdamSLevy** [comment]
Thanks for the clarification.

**Comment by rusenask** [comment]
Would it be possible to have `GetLastError()` on the wasmer instance itself rather than a global one? 

This way it would be easier to manage locks and state from the user's perspective (if we run multiple parallel wasm instances).

**Comment by AdamSLevy** [comment]
It seems like the error could be checked and returned as part of the actual Wasm function call. If that was part of the closure around the wasm call that is saved in an Instances Exports, then the LockOSThread could be scoped to just that closure and would result in the least amount of time in the lock for any given Wasm call and error cycle.

**Comment by Hywan** [comment]
Indeed. That was my idea. @AdamSLevy Are you willing to implement that in a PR? Otherwise I will handle that.

**Comment by AdamSLevy** [comment]
I'd be happy to take a crack at it tomorrow.

**Comment by Hywan** [comment]
:+1:

**Comment by Hywan** [comment]
Closed in favor of https://github.com/wasmerio/wasmer-go/pull/185. Thanks for the inspiration!
